//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OHAHA.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string Residency { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
    }
}
