//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OHAHA.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanID { get; set; }
        public int ClientId { get; set; }
        public int Loan_AMT { get; set; }
        public int Interest { get; set; }
        public string Term { get; set; }
        public string NoOf_Payment { get; set; }
        public int Deduction { get; set; }
        public int Interested_AMT { get; set; }
        public int Receivable_AMT { get; set; }
        public int Total_Payable { get; set; }
        public System.DateTime Due_Date { get; set; }
        public string Status { get; set; }
    }
}
